#ifndef _LIBENCLOUD_PRIV_API_H_
#define _LIBENCLOUD_PRIV_API_H_

#include <encloud/Common>
#include <encloud/Server>

//
// defaults
//
#define LIBENCLOUD_API_SCHEME       "http"
#define LIBENCLOUD_API_HOST         "localhost"
#define LIBENCLOUD_API_PORT         LIBENCLOUD_SRV_PORT_DFT
#define LIBENCLOUD_API_URL          LIBENCLOUD_API_SCHEME "://" LIBENCLOUD_API_HOST ":" \
                                    LIBENCLOUD_MACRO_STR(LIBENCLOUD_API_PORT)

//
// API definitions
//
#define LIBENCLOUD_API_VERSION      "1"
#define LIBENCLOUD_API_PREFIX_PATH  "/api_v" LIBENCLOUD_API_VERSION
#define LIBENCLOUD_API_STATUS_PATH  LIBENCLOUD_API_PREFIX_PATH"/status"
#define LIBENCLOUD_API_AUTH_PATH    LIBENCLOUD_API_PREFIX_PATH"/auth"
#define LIBENCLOUD_API_SETUP_PATH   LIBENCLOUD_API_PREFIX_PATH"/setup"
#define LIBENCLOUD_API_CLOUD_PATH   LIBENCLOUD_API_PREFIX_PATH"/cloud"

#endif  // _LIBENCLOUD_PRIV_API_H_
